import { IData } from '../../types';

const DATA: IData[] = [
    {
        num: '1',
        name: 'Большой шар с рисунком',
        count: '2',
        year: '1960',
        shape: 'шар',
        color: 'желтый',
        size: 'большой',
        img: 'https://i.ibb.co/DQhrh4T/id1.png',
        favorite: false,
    },
    {
        num: '2',
        name: 'Зелёный шар с цветами',
        count: '5',
        year: '2000',
        shape: 'шар',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/YQtGGfn/2.png',
        favorite: false,
    },
    {
        num: '3',
        name: 'Красный матовый шар',
        count: '3',
        year: '1990',
        shape: 'шар',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/hKXjQhS/3.png',
        favorite: false,
    },
    {
        num: '4',
        name: 'Сосулька красная',
        count: '2',
        year: '1980',
        shape: 'фигурка',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/bdR2xfM/4.png',
        favorite: false,
    },
    {
        num: '5',
        name: 'Красный виноград',
        count: '4',
        year: '1980',
        shape: 'фигурка',
        color: 'красный',
        size: 'средний',
        img: 'https://i.ibb.co/c81CYk9/5.png',
        favorite: true,
    },
    {
        num: '6',
        name: 'Красный шар с рисунком',
        count: '6',
        year: '2010',
        shape: 'шар',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/GsQFMRk/6.png',
        favorite: false,
    },
    {
        num: '7',
        name: 'Молочно-белый шар',
        count: '12',
        year: '1960',
        shape: 'шар',
        color: 'белый',
        size: 'средний',
        img: 'https://i.ibb.co/h8mRHKP/7.png',
        favorite: true,
    },
    {
        num: '8',
        name: 'Красный шар',
        count: '10',
        year: '2010',
        shape: 'шар',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/D1HRXr0/8.png',
        favorite: false,
    },
    {
        num: '9',
        name: 'Белый шар ретро',
        count: '7',
        year: '1960',
        shape: 'шар',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/m0VhK5K/9.png',
        favorite: false,
    },
    {
        num: '10',
        name: 'Белый шар с цветами',
        count: '5',
        year: '1980',
        shape: 'шар',
        color: 'белый',
        img: 'https://i.ibb.co/XSQGxY6/10.png',
        size: 'большой',

        favorite: false,
    },
    {
        num: '11',
        name: 'Шар расписной Река',
        count: '3',
        year: '1970',
        shape: 'шар',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/gVgGb22/11.png',
        favorite: true,
    },
    {
        num: '12',
        name: 'Шар расписной Деревня',
        count: '4',
        year: '1970',
        shape: 'шар',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/StQVmpH/12.png',
        favorite: true,
    },
    {
        num: '13',
        name: 'Желтый шар с бантом',
        count: '2',
        year: '2010',
        shape: 'шар',
        color: 'желтый',
        size: 'большой',
        img: 'https://i.ibb.co/MSfZfYj/13.png',
        favorite: false,
    },
    {
        num: '14',
        name: 'Желтый шар с паетками',
        count: '12',
        year: '1980',
        shape: 'шар',
        color: 'желтый',
        size: 'большой',
        img: 'https://i.ibb.co/F35Q07L/14.png',
        favorite: false,
    },
    {
        num: '15',
        name: 'Снежинка изящная',
        count: '1',
        year: '1940',
        shape: 'снежинка',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/grGtqmz/15.png',
        favorite: false,
    },
    {
        num: '16',
        name: 'Розовый шар с блёстками',
        count: '12',
        year: '2010',
        shape: 'шар',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/5YLswyr/16.png',
        favorite: false,
    },
    {
        num: '17',
        name: 'Рубиново-золотой шар',
        count: '8',
        year: '1960',
        shape: 'шар',
        color: 'желтый',
        size: 'большой',
        img: 'https://i.ibb.co/brfsGsK/17.png',
        favorite: false,
    },
    {
        num: '18',
        name: 'Фигурка Лис в шарфе',
        count: '8',
        year: '1950',
        shape: 'фигурка',
        color: 'желтый',
        size: 'средний',
        img: 'https://i.ibb.co/LSKHX5p/18.png',
        favorite: true,
    },
    {
        num: '19',
        name: 'Красная снежинка',
        count: '6',
        year: '1990',
        shape: 'снежинка',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/WkhBKzg/19.png',
        favorite: false,
    },
    {
        num: '20',
        name: 'Снежинка золотая',
        count: '12',
        year: '2020',
        shape: 'снежинка',
        color: 'желтый',
        size: 'большой',
        img: 'https://i.ibb.co/mHsztd8/20.png',
        favorite: false,
    },
    {
        num: '21',
        name: 'Снежинка арктическая',
        count: '11',
        year: '2020',
        shape: 'снежинка',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/Vmg9DF6/21.png',
        favorite: false,
    },
    {
        num: '22',
        name: 'Снежинка двухцветная',
        count: '6',
        year: '1960',
        shape: 'снежинка',
        color: 'красный',
        size: 'большой',
        img: 'https://i.ibb.co/pbHGQqX/22.png',
        favorite: false,
    },
    {
        num: '23',
        name: 'Фигурка Ангела',
        count: '11',
        year: '1940',
        shape: 'фигурка',
        color: 'красный',
        size: 'средний',
        img: 'https://i.ibb.co/y0pkHqJ/23.png',
        favorite: true,
    },
    {
        num: '24',
        name: 'Снежинка новогодняя',
        count: '1',
        year: '1980',
        shape: 'снежинка',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/ZdPKhst/24.png',
        favorite: false,
    },
    {
        num: '25',
        name: 'Фигурка Мухомор',
        count: '10',
        year: '1950',
        shape: 'фигурка',
        color: 'красный',
        size: 'малый',
        img: 'https://i.ibb.co/98HJtXs/25.png',
        favorite: false,
    },
    {
        num: '26',
        name: 'Снежинка серебристая',
        count: '6',
        year: '2020',
        shape: 'снежинка',
        color: 'белый',
        size: 'большой',
        img: 'https://i.ibb.co/jMVrxpD/26.png',
        favorite: false,
    },
    {
        num: '27',
        name: 'Пряничный домик',
        count: '1',
        year: '1940',
        shape: 'фигурка',
        color: 'желтый',
        size: 'большой',
        img: 'https://i.ibb.co/0spqqNs/27.png',
        favorite: false,
    },
    {
        num: '28',
        name: 'Пряничный теремок',
        count: '1',
        year: '1940',
        shape: 'фигурка',
        color: 'желтый',
        size: 'малый',
        img: 'https://i.ibb.co/92wCwHH/28.png',
        favorite: false,
    },
    {
        num: '29',
        name: 'Пряничная избушка',
        count: '1',
        year: '1940',
        shape: 'фигурка',
        color: 'желтый',
        size: 'средний',
        img: 'https://i.ibb.co/zVKCL0q/29.png',
        favorite: false,
    },
    {
        num: '30',
        name: 'Фигурка белого медведя',
        count: '2',
        year: '1980',
        shape: 'фигурка',
        color: 'белый',
        size: 'средний',
        img: 'https://i.ibb.co/6rssTb5/30.png',
        favorite: false,
    },
];

export default DATA;
